WHITELIST_APPLICATION_V1 = "whitelist_application_v1"
RED_SHIELD_APPLICATION_V1 = "red_shield_application_v1"
CREDIT_APPLICATION_V1 = "credit_application_v1"

SUPPORTED_PRODUCT_HANDLERS = {
    WHITELIST_APPLICATION_V1,
    RED_SHIELD_APPLICATION_V1,
    CREDIT_APPLICATION_V1,
}
