# Generated by Django 4.1.13 on 2026-07-03 23:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("workflow_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("kind", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("product", models.CharField(blank=True, default="", max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("retrying", "Retrying"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancel_requested", "Cancel requested"),
                            ("cancelled", "Cancelled"),
                            ("timed_out", "Timed out"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("stage", models.CharField(default="created", max_length=128)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("payload", models.JSONField(default=dict)),
                ("result", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("trace_id", models.CharField(db_index=True, max_length=128)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("attempt_count", models.PositiveIntegerField(default=1)),
                ("timeout_seconds", models.PositiveIntegerField(default=300)),
                ("deadline_at", models.DateTimeField(blank=True, null=True)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=128),
                ),
                ("cancel_requested_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("celery_task_id", models.CharField(blank=True, default="", max_length=128)),
                ("attempt", models.PositiveIntegerField(default=1)),
                ("level", models.CharField(default="INFO", max_length=16)),
                ("step", models.CharField(blank=True, default="", max_length=128)),
                ("message", models.TextField()),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="JobApiCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("celery_task_id", models.CharField(blank=True, default="", max_length=128)),
                ("attempt", models.PositiveIntegerField(default=1)),
                ("step", models.CharField(blank=True, default="", max_length=128)),
                ("method", models.CharField(max_length=16)),
                ("url", models.TextField()),
                ("request_headers", models.JSONField(default=dict)),
                ("request_body", models.JSONField(blank=True, null=True)),
                ("response_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("response_headers", models.JSONField(default=dict)),
                ("response_body", models.JSONField(blank=True, null=True)),
                ("response_truncated", models.BooleanField(default=False)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("error_type", models.CharField(blank=True, default="", max_length=128)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_calls",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["status", "expires_at"], name="job_status_exp_idx"),
        ),
        migrations.AddIndex(
            model_name="joblog",
            index=models.Index(fields=["job", "id"], name="job_log_job_id_idx"),
        ),
        migrations.AddIndex(
            model_name="jobapicall",
            index=models.Index(fields=["job", "id"], name="job_call_job_id_idx"),
        ),
    ]
